# Default values for antmedia-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: antmedia/enterprise
  tag: 2.5.3
  pullPolicy: IfNotPresent
