kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/"
---
{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-volume-claim
  {{- if .Values.persistence.config.skipuninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end -}}