name: Build and Push Docker Image
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download latest.zip
        run: wget --quiet ${{ secrets.LATEST_URL }}

      - name: Download Dockerfile
        run: wget --quiet https://raw.githubusercontent.com/ant-media/Scripts/master/docker/Dockerfile_Process -O Dockerfile

      - name: Read version from VERSION file
        id: read-version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Build Docker image
        run: docker build --network=host -t antmediaserver:${{ steps.read-version.outputs.version }} --build-arg AntMediaServer=latest.zip .

      - name: Tag Docker image
        run: |
          docker tag $(docker images --format "{{.ID}}" --filter "reference=antmediaserver:${{ steps.read-version.outputs.version }}") antmedia/enterprise:${{ steps.read-version.outputs.version }}
          docker tag $(docker images --format "{{.ID}}" --filter "reference=antmediaserver:${{ steps.read-version.outputs.version }}") antmedia/enterprise:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push antmedia/enterprise:${{ steps.read-version.outputs.version }}
          docker push antmedia/enterprise:latest
