name: Build and Push Docker Image
on:
  pull_request:

jobs:
  build-and-push:
    #if: contains(github.event.head_commit.modified, 'VERSION')
    #if: contains(github.event.modified_files, 'VERSION')
    #if: ${{ github.event_changes.VERSION }}
    #if: github.event.head_commit.modified_files contains 'VERSION'
    if: ${{ contains(github.event.head_commit.message, 'VERSION') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download latest.zip
        run: wget --quiet ${{ secrets.LATEST_URL }}

      - name: Download Dockerfile
        run: wget --quiet https://raw.githubusercontent.com/ant-media/Scripts/master/docker/Dockerfile_Process -O Dockerfile

      - name: Read version from VERSION file
        id: read-version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Set image name
        id: set-image-name
        run: echo "IMAGE_NAME=muratugureminoglu/antmedia" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build --network=host -t antmediaserver:${{ steps.read-version.outputs.version }} --build-arg AntMediaServer=latest.zip .

      - name: Tag Docker image
        run: |
          docker tag $(docker images --format "{{.ID}}" --filter "reference=antmediaserver:${{ steps.read-version.outputs.version }}") ${{ env.IMAGE_NAME }}:${{ steps.read-version.outputs.version }}
          docker tag $(docker images --format "{{.ID}}" --filter "reference=antmediaserver:${{ steps.read-version.outputs.version }}") ${{ env.IMAGE_NAME }}:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ steps.read-version.outputs.version }}
          docker push ${{ env.IMAGE_NAME }}:latest
