name: Helm Chart Test

on:
  push:
    branches:
      - master  # Replace with your main branch name or specify branches to trigger the workflow on
  pull_request:
    branches:
      - master  # Replace with your main branch name or specify branches to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest  # Choose the appropriate runner for your needs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1  # You can use a different Helm setup action based on your requirements

      - name: Install dependencies
        run: |
          helm init
          helm dependency update .

      - name: Lint Helm chart
        run: |
          helm lint .

      # Add additional steps here for running further tests, such as integration tests, validation checks, or any other Helm-related tests.

