name: Internal Tests

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/package.sh'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Push changes
        run: |
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
