name: Internal Tests

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/package.sh'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          path: ${{ github.event.repository.name }}
      - name: Push changes
        run: |
          echo "Env: ${{ github.event.inputs.environment }}" 
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Branch: ${{ github.event.repository.name }}"
          echo "Ref: ${{ github.event.client_payload.pull_request.head.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
