name: Internal Tests

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/package.sh'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get staging branch name
        id: branch_name
        run: echo "staging_branch=$(git for-each-ref --format='%(refname:short)' refs/heads/staging*)" >> $GITHUB_OUTPUT
      - name: Push changes
        run: |
          echo "Branch: ${{ steps.branch_name.outputs.staging_branch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
